### PR TITLE
feat: Add jsrepo

### PR DESCRIPTION
**Pull request by ieedan**
First of all this is super cool I love that it looks just like lucide but with animations!

I am working on a project [jsrepo](https://github.com/ieedan/jsrepo) that is really nice for stuff like this where you want to copy paste things into your project (it also does a bunch more than just copy paste).

This PR integrates jsrepo so that you can add the icons from the CLI into your project like:
```bash
jsrepo add icons/alarm-clock-check
```

If you want to try it out you can use this branch when you initialize jsrepo:
```
github/ieedan/icons/tree/jsrepo
```

## Changes
- Add `build:registry` command to build the `jsrepo-manifest.json`
- Add a workflow to PR when the manifest changes so that you are always up to date
- Add a button to copy the jsrepo command to the clipboard

Feel free to tell me to fuck off and close this but I think it's pretty cool!

P.S. Sorry for the size most of it is the manifest

### CODE REVIEW

**Comment by jis3r** [comment]
Hey, first of all thank you for the idea and the submission! I am actually currently working on packaging this repo for npm. I totally see the benefit of jsrepo and I am thinking about using it for some project maybe. For these icons though, I am leaning towards a package, because you usually want to use multiple icons throughout your whole project or application. If you used lucide before, you would then be able to just import the same icons from this library instead of lucide. I was also thinking about adding installation possibilities via npx. Curious to hear your opinion on this, especially what the benefit of jsrepo over npx is.

**Comment by jis3r** [comment]
I meant the possibility to add specific icons via npx, just like shadcn

**Comment by ieedan** [comment]
Honestly I would agree with you most of the time you don't want to just install a single icon. I was thinking jsrepo would be a good fit for what this project currently does not necessarily if you want users to be able to use it like lucide.

I still think it may be cool to offer both though! For me I think this would be nice to use but my large svelte project at work already won't build on free runners because of it's size and the amount of dependencies.

**Comment by ieedan** [comment]
> I meant the possibility to add specific icons via npx, just like shadcn

If you are looking to build your own shadcn then don't this does it for you and it's better.

**Comment by ieedan** [comment]
For the record jsrepo also lists icons in your repo so you don't have to explicitly provide them:
```
jsrepo add
```

This will list all the `blocks` in your repo

**Comment by ieedan** [comment]
If you have the time you can check out the docs or demos as well that might give you a better picture of what it actually is.

I think if you were looking to build something like shadcn then this would be a shortcut for you!

**Comment by jis3r** [comment]
> Curious to hear your opinion on this, especially what the benefit of jsrepo over npx is.

But where would be the difference between adding a bin script to the package and using jsrepo? Both do the same in the end or am I missing something?

**Comment by ieedan** [comment]
You would need to write the bin script yourself. Or do you mean using jsrepo as your bin script?

jsrepo also does a lot more than just adding them into your project if you look at the `update` or `diff` command as well as stuff like formatting the code when it comes into your project.

**Comment by ieedan** [comment]
The flow for the user would look something like:
```
# initialize jsrepo
npx jsrepo init

# add icons through the list
npx jsrepo add

# add icon by name
npx jsrepo add icons/alarm-clock-check
```

In this case jsrepo is your cli for adding the icons.

**Pull request closed without merging**
