### PR TITLE
add: upload icon

### PR DESCRIPTION
**Pull request by oMaN-Rod**

### CODE REVIEW

**Comment by jis3r** [comment]
Could you please add a short video of the animation? :) 

Forgot to add that to the contribution md

**Comment by jis3r** [comment]
And pls add size and strokeWidth as props to the icon. I just extended all icons with those props 2hrs ago. If you pull the latest commits you should see the changes :)

**Comment by oMaN-Rod** [comment]
I duplicated the download icon and swapped out the svg, the animation for this icon is the inverse, i.e., arrow moves 2px up.

**Review by jis3r — APPROVED** [review]

**Comment by jis3r** [comment]
Nice, thank you for the contribution! I also just realised that Vercel creates preview deployments so there won't be any need for videos in the future. :)

**Pull request merged**
